[pytest]
# Регистрация кастомных маркеров
markers =
    smoke: Маркер для дымовых тестов
    regression: Маркер для регрессионных тестов
    api: Маркер для API тестов

# Параметры запуска по умолчанию
addopts =
    -v
    -s
    --alluredir=reports
    --maxfail=1
    --tb=short

# Папка с тестами
testpaths = tests

# Фильтрация предупреждений
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning